// <auto-generated />
using System;
using ForecastExceptionPortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastExceptionPortal.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714161033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("ForecastExceptionPortal.Api.Models.ExceptionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Customers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustomersVariancePct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExceptionScore")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedCustomers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedSales")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sales")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesVariancePct")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
